#!/usr/bin/env python3
"""Raptor Cortex behavioural + wiring tests.

These are behavioural rather than textual: cortex-helper is extracted and
actually executed against stubbed privileged commands, so the assertions
reflect what the helper really does on a live system.

Two bugs this file exists to prevent, both found by inspection on 2026-09-28
and neither of which the build or the existing tests would ever have caught:

  1. `trim-background` and `restore-background` each declared their own
     BACKGROUND_PROCS array and the two had drifted: 20 processes were
     SIGSTOPped, only 13 were ever SIGCONT'd. The other 7 stayed frozen for
     the rest of the session. Two of them were `dpkg` and `apt-get` — a
     SIGSTOPped dpkg holds the dpkg lock, so every later apt invocation hung
     until reboot.

  2. The GUI's "Restore Desktop" action called `cortex-helper
     resume-background`, which is not a real action. It fell through to the
     usage arm and exited 1, so the call silently did nothing while the UI
     toasted "all services resumed". The seven frozen processes above were
     never recovered.

Run:  python3 files/scripts/tests/test_cortex.py
"""
from __future__ import annotations

import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent
sys.path.insert(0, str(HERE))

from extract import extract_file  # noqa: E402

HELPER_PATH = "/usr/lib/raptor/cortex-helper"
GUI_PATH = "/usr/bin/raptor-cortex"

# Commands cortex-helper shells out to while trimming/restoring. Stubbed so the
# test can observe intent without touching the real system.
_STUBS = ("pkill", "systemctl", "balooctl6", "ionice", "renice", "pgrep",
          "drop_caches", "zramctl", "powerprofilesctl")


def _extract_helper() -> Path:
    payload = extract_file(SCRIPTS / "raptor-cortex.sh")
    assert HELPER_PATH in payload, f"{HELPER_PATH} not generated by raptor-cortex.sh"
    dest = Path(tempfile.mkdtemp(prefix="raptor-cortex-helper-")) / "cortex-helper"
    dest.write_text(payload[HELPER_PATH])
    dest.chmod(dest.stat().st_mode | stat.S_IEXEC)
    return dest


def _extract_gui() -> str:
    payload = extract_file(SCRIPTS / "raptor-cortex.sh")
    assert GUI_PATH in payload, f"{GUI_PATH} not generated by raptor-cortex.sh"
    return payload[GUI_PATH]


def _stub_dir(tmp: Path) -> Path:
    """A PATH prefix where every privileged command logs its argv and exits 0."""
    d = tmp / "bin"
    d.mkdir()
    for name in _STUBS:
        log = tmp / f"{name}.log"
        p = d / name
        p.write_text(f'#!/bin/sh\nprintf "%s\\n" "$*" >> "{log}"\nexit 0\n')
        p.chmod(0o755)
    return d


def _signals(helper: Path, action: str, tmp: Path) -> list[str]:
    """Run `helper action` with stubs and return the processes it signalled."""
    log = tmp / "pkill.log"
    log.unlink(missing_ok=True)
    env = dict(os.environ, PATH=f"{tmp / 'bin'}:{os.environ['PATH']}")
    # Kernel-level writes (/proc/sys) are not redirected by PATH, so the
    # helper's own `|| true` guards are what keep this safe; run it in a
    # throwaway mount-free environment with writes to /proc simply failing.
    proc = subprocess.run([str(helper), action], capture_output=True,
                          text=True, env=env, timeout=60)
    if proc.returncode != 0:
        raise AssertionError(
            f"cortex-helper {action} exited {proc.returncode}\n"
            f"stdout: {proc.stdout}\nstderr: {proc.stderr}"
        )
    if not log.exists():
        return []
    return [ln.split()[1] for ln in log.read_text().splitlines()
            if ln.strip()]


class TestCortexHelperActions(unittest.TestCase):
    """The helper's own action table."""

    @classmethod
    def setUpClass(cls):
        cls.helper = _extract_helper()
        cls.tmp = Path(tempfile.mkdtemp(prefix="raptor-cortex-run-"))
        cls.stub = _stub_dir(cls.tmp)

    def test_helper_is_valid_bash(self):
        proc = subprocess.run(["bash", "-n", str(self.helper)],
                              capture_output=True, text=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)

    def test_background_procs_declared_exactly_once(self):
        """One declaration, so trim and restore cannot drift apart again."""
        text = self.helper.read_text()
        decls = re.findall(r"^BACKGROUND_PROCS=\(", text, re.M)
        self.assertEqual(
            len(decls), 1,
            "BACKGROUND_PROCS must be declared exactly once at helper scope and "
            f"reused by both actions; found {len(decls)} declarations",
        )

    def test_trim_and_restore_signal_identical_sets(self):
        """Every process stopped must be resumed.

        This is the core regression. A process left SIGSTOPped stays frozen
        until reboot, so the two actions must signal the same name set.
        """
        stopped = _signals(self.helper, "trim-background", self.tmp)
        resumed = _signals(self.helper, "restore-background", self.tmp)
        self.assertTrue(stopped, "trim-background signalled nothing")
        orphaned = sorted(set(stopped) - set(resumed))
        self.assertEqual(
            orphaned, [],
            "trim-background stops these but restore-background never resumes "
            "them — they stay SIGSTOPped for the rest of the session: "
            f"{orphaned}",
        )
        self.assertEqual(
            sorted(stopped), sorted(resumed),
            "restore-background resumes processes trim-background never stopped",
        )

    def test_package_transaction_tools_are_never_sigstopped(self):
        """dpkg/apt/apt-get hold locks. SIGSTOPping them can wedge the box.

        A frozen dpkg keeps /var/lib/dpkg/lock-frontend held, so every
        subsequent apt invocation blocks forever. These are handled by
        systemd stop where needed, never by SIGSTOP.
        """
        text = self.helper.read_text()
        match = re.search(r"^BACKGROUND_PROCS=\(\n(.*?)\n\)", text, re.S | re.M)
        self.assertIsNotNone(match, "BACKGROUND_PROCS not found")
        blocked = {"dpkg", "apt", "apt-get", "unattended-upgrade"}
        present = blocked & set(re.findall(r'"([^"]+)"', match.group(1)))
        self.assertEqual(
            present, set(),
            f"package-transaction tools must not be SIGSTOPped: {sorted(present)}",
        )

    def test_restore_background_is_a_real_action(self):
        """`restore-background` must not fall through to the usage arm."""
        proc = subprocess.run([str(self.helper), "restore-background"],
                              capture_output=True, text=True, timeout=60)
        self.assertNotEqual(proc.returncode, 1,
                            "restore-background fell through to the usage arm")
        self.assertNotIn("Usage: cortex-helper", proc.stdout)

    def test_usage_lists_every_real_action(self):
        text = self.helper.read_text()
        proc = subprocess.run([str(self.helper), "definitely-not-an-action"],
                              capture_output=True, text=True)
        self.assertEqual(proc.returncode, 1)
        usage = proc.stdout
        self.assertIn("trim-background", usage)
        self.assertIn("restore-background", usage)
        self.assertIn("set-mode", usage)


class TestCortexGuiCallsRealActions(unittest.TestCase):
    """The GUI may only invoke helper actions that actually exist.

    Guards bug 2 in general form: a typo'd or renamed action silently exits 1
    through the usage arm, so the button appears to work and changes nothing.
    """

    @classmethod
    def setUpClass(cls):
        payload = extract_file(SCRIPTS / "raptor-cortex.sh")
        cls.helper_src = payload[HELPER_PATH]
        cls.gui_src = payload[GUI_PATH]

    def _valid_actions(self) -> set[str]:
        """Action names the helper's `case "$ACTION"` dispatch accepts."""
        case = re.search(r'case\s+"\$ACTION"\s+in\n(.*?)^esac',
                         self.helper_src, re.S | re.M)
        self.assertIsNotNone(case, "could not locate the helper's case dispatch")
        actions: set[str] = set()
        for arm in re.findall(r"^    ([^)\n]+)\)", case.group(1), re.M):
            actions |= {a.strip() for a in arm.split("|") if a.strip()}
        actions.discard("*")
        return actions

    def test_gui_only_calls_existing_helper_actions(self):
        valid = self._valid_actions()
        self.assertIn("restore-background", valid,
                      "helper lost its restore action entirely")
        called: set[str] = set()
        # e.g. subprocess.run(["sudo", HELPER, "restore-background"], ...)
        for call in re.findall(r"HELPER\s*,\s*[\"']([^\"']+)[\"']", self.gui_src):
            called.add(call)
        bad = sorted(called - valid)
        self.assertEqual(
            bad, [],
            f"the GUI calls helper actions that do not exist: {bad}. The helper "
            "exits 1 on an unknown action, so these calls silently do nothing "
            f"while the UI reports success. Valid actions: {sorted(valid)}",
        )

    def test_gui_does_not_report_unverified_success(self):
        """Any toast claiming a restore happened must come from a checked call.

        The old code toasted "all services resumed" unconditionally, before
        knowing whether the helper had run at all.
        """
        self.assertNotIn(
            "resume-background", self.gui_src,
            "GUI still calls the non-existent resume-background action",
        )
        resume_fn = re.search(
            r"def _run_restore_background\(self\):(.*?)(?=\n    def )",
            self.gui_src, re.S)
        self.assertIsNotNone(resume_fn, "_run_restore_background missing")
        body = resume_fn.group(1)
        self.assertIn("returncode", body,
                      "restore must check the helper's exit status")
        self.assertIn("_toast_error", body,
                      "a failed restore must be reported, not swallowed")


class TestCortexSudoers(unittest.TestCase):
    """The helper is only reachable because of this sudoers grant."""

    def test_sudoers_grants_the_helper_without_password(self):
        payload = extract_file(SCRIPTS / "raptor-cortex.sh")
        rule = payload["/etc/sudoers.d/raptor-cortex"]
        self.assertIn("NOPASSWD", rule)
        self.assertIn(HELPER_PATH, rule)


class TestSudoersAlwaysValidated(unittest.TestCase):
    """Every sudoers drop-in must be validated, and validation must be fatal.

    sudo silently ignores an entire malformed file in /etc/sudoers.d. So an
    unvalidated drop-in that goes bad ships green in CI and then breaks every
    privileged call in the app for every user, with nothing in the logs.
    """

    def _sudoers_paths(self, installer: Path) -> list[str]:
        return [p for p in extract_file(installer) if "/sudoers.d/" in p]

    def test_every_sudoers_dropin_is_visudo_validated(self):
        found_any = False
        for installer in sorted(SCRIPTS.glob("*.sh")):
            for path in self._sudoers_paths(installer):
                found_any = True
                with self.subTest(installer=installer.name, dropin=path):
                    text = installer.read_text()
                    self.assertIn(
                        "visudo", text,
                        f"{installer.name} writes {path} but never validates it — "
                        "sudo ignores a malformed drop-in entirely, so a bad "
                        "file silently breaks the app for everyone",
                    )
                    self.assertNotIn(
                        f"visudo -cf {path} || true", text,
                        f"{installer.name}: sudoers validation of {path} is "
                        "discarded, so a broken file ships silently",
                    )
                    self.assertNotIn(
                        f"visudo -c -f {path} >/dev/null &&", text,
                        f"{installer.name}: sudoers validation of {path} is "
                        "chained with && so a failure cannot stop the build",
                    )
        self.assertTrue(found_any, "no sudoers drop-ins found — tests are vacuous")


if __name__ == "__main__":
    unittest.main(verbosity=2)
