#!/usr/bin/env python3
"""Raptor Cortex behavioural + wiring tests.

These are behavioural rather than textual: cortex-helper is extracted and
actually executed against stubbed privileged commands, so the assertions
reflect what the helper really does on a live system.

Two bugs this file exists to prevent, both found by inspection on 2026-09-28
and neither of which the build or the existing tests would ever have caught:

  1. `trim-background` and `restore-background` each declared their own
     BACKGROUND_PROCS array and the two had drifted: 20 processes were
     SIGSTOPped, only 13 were ever SIGCONT'd. The other 7 stayed frozen for
     the rest of the session. Two of them were `dpkg` and `apt-get` — a
     SIGSTOPped dpkg holds the dpkg lock, so every later apt invocation hung
     until reboot.

  2. The GUI's "Restore Desktop" action called `cortex-helper
     resume-background`, which is not a real action. It fell through to the
     usage arm and exited 1, so the call silently did nothing while the UI
     toasted "all services resumed". The seven frozen processes above were
     never recovered.

Run:  python3 files/scripts/tests/test_cortex.py
"""
from __future__ import annotations

import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent
sys.path.insert(0, str(HERE))

from extract import extract_file  # noqa: E402

HELPER_PATH = "/usr/lib/raptor/cortex-helper"
GUI_PATH = "/usr/bin/raptor-cortex"

# Commands cortex-helper shells out to while trimming/restoring. Stubbed so the
# test can observe intent without touching the real system.
_STUBS = ("pkill", "systemctl", "balooctl6", "ionice", "renice", "pgrep",
          "drop_caches", "zramctl", "powerprofilesctl")


def _extract_helper() -> Path:
    payload = extract_file(SCRIPTS / "raptor-cortex.sh")
    assert HELPER_PATH in payload, f"{HELPER_PATH} not generated by raptor-cortex.sh"
    dest = Path(tempfile.mkdtemp(prefix="raptor-cortex-helper-")) / "cortex-helper"
    dest.write_text(payload[HELPER_PATH])
    dest.chmod(dest.stat().st_mode | stat.S_IEXEC)
    return dest


def _extract_gui() -> str:
    payload = extract_file(SCRIPTS / "raptor-cortex.sh")
    assert GUI_PATH in payload, f"{GUI_PATH} not generated by raptor-cortex.sh"
    return payload[GUI_PATH]


def _stub_dir(tmp: Path) -> Path:
    """A PATH prefix where every privileged command logs its argv and exits 0."""
    d = tmp / "bin"
    d.mkdir()
    for name in _STUBS:
        log = tmp / f"{name}.log"
        p = d / name
        p.write_text(f'#!/bin/sh\nprintf "%s\\n" "$*" >> "{log}"\nexit 0\n')
        p.chmod(0o755)
    return d


def _signals(helper: Path, action: str, tmp: Path) -> list[str]:
    """Run `helper action` with stubs and return the processes it signalled."""
    log = tmp / "pkill.log"
    log.unlink(missing_ok=True)
    env = dict(os.environ, PATH=f"{tmp / 'bin'}:{os.environ['PATH']}")
    # Kernel-level writes (/proc/sys) are not redirected by PATH, so the
    # helper's own `|| true` guards are what keep this safe; run it in a
    # throwaway mount-free environment with writes to /proc simply failing.
    proc = subprocess.run([str(helper), action], capture_output=True,
                          text=True, env=env, timeout=60)
    if proc.returncode != 0:
        raise AssertionError(
            f"cortex-helper {action} exited {proc.returncode}\n"
            f"stdout: {proc.stdout}\nstderr: {proc.stderr}"
        )
    if not log.exists():
        return []
    return [ln.split()[1] for ln in log.read_text().splitlines()
            if ln.strip()]


class TestCortexHelperActions(unittest.TestCase):
    """The helper's own action table."""

    @classmethod
    def setUpClass(cls):
        cls.helper = _extract_helper()
        cls.tmp = Path(tempfile.mkdtemp(prefix="raptor-cortex-run-"))
        cls.stub = _stub_dir(cls.tmp)

    def test_helper_is_valid_bash(self):
        proc = subprocess.run(["bash", "-n", str(self.helper)],
                              capture_output=True, text=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)

    def test_background_procs_declared_exactly_once(self):
        """One declaration, so trim and restore cannot drift apart again."""
        text = self.helper.read_text()
        decls = re.findall(r"^BACKGROUND_PROCS=\(", text, re.M)
        self.assertEqual(
            len(decls), 1,
            "BACKGROUND_PROCS must be declared exactly once at helper scope and "
            f"reused by both actions; found {len(decls)} declarations",
        )

    def test_trim_and_restore_signal_identical_sets(self):
        """Every process stopped must be resumed.

        This is the core regression. A process left SIGSTOPped stays frozen
        until reboot, so the two actions must signal the same name set.
        """
        stopped = _signals(self.helper, "trim-background", self.tmp)
        resumed = _signals(self.helper, "restore-background", self.tmp)
        self.assertTrue(stopped, "trim-background signalled nothing")
        orphaned = sorted(set(stopped) - set(resumed))
        self.assertEqual(
            orphaned, [],
            "trim-background stops these but restore-background never resumes "
            "them — they stay SIGSTOPped for the rest of the session: "
            f"{orphaned}",
        )
        self.assertEqual(
            sorted(stopped), sorted(resumed),
            "restore-background resumes processes trim-background never stopped",
        )

    def test_package_transaction_tools_are_never_sigstopped(self):
        """dpkg/apt/apt-get hold locks. SIGSTOPping them can wedge the box.

        A frozen dpkg keeps /var/lib/dpkg/lock-frontend held, so every
        subsequent apt invocation blocks forever. These are handled by
        systemd stop where needed, never by SIGSTOP.
        """
        text = self.helper.read_text()
        match = re.search(r"^BACKGROUND_PROCS=\(\n(.*?)\n\)", text, re.S | re.M)
        self.assertIsNotNone(match, "BACKGROUND_PROCS not found")
        blocked = {"dpkg", "apt", "apt-get", "unattended-upgrade"}
        present = blocked & set(re.findall(r'"([^"]+)"', match.group(1)))
        self.assertEqual(
            present, set(),
            f"package-transaction tools must not be SIGSTOPped: {sorted(present)}",
        )

    def test_restore_background_is_a_real_action(self):
        """`restore-background` must not fall through to the usage arm."""
        proc = subprocess.run([str(self.helper), "restore-background"],
                              capture_output=True, text=True, timeout=60)
        self.assertNotEqual(proc.returncode, 1,
                            "restore-background fell through to the usage arm")
        self.assertNotIn("Usage: cortex-helper", proc.stdout)

    def test_usage_lists_every_real_action(self):
        text = self.helper.read_text()
        proc = subprocess.run([str(self.helper), "definitely-not-an-action"],
                              capture_output=True, text=True)
        self.assertEqual(proc.returncode, 1)
        usage = proc.stdout
        self.assertIn("trim-background", usage)
        self.assertIn("restore-background", usage)
        self.assertIn("set-mode", usage)


class TestCortexGuiCallsRealActions(unittest.TestCase):
    """The GUI may only invoke helper actions that actually exist.

    Guards bug 2 in general form: a typo'd or renamed action silently exits 1
    through the usage arm, so the button appears to work and changes nothing.
    """

    @classmethod
    def setUpClass(cls):
        payload = extract_file(SCRIPTS / "raptor-cortex.sh")
        cls.helper_src = payload[HELPER_PATH]
        cls.gui_src = payload[GUI_PATH]

    def _valid_actions(self) -> set[str]:
        """Action names the helper's `case "$ACTION"` dispatch accepts."""
        case = re.search(r'case\s+"\$ACTION"\s+in\n(.*?)^esac',
                         self.helper_src, re.S | re.M)
        self.assertIsNotNone(case, "could not locate the helper's case dispatch")
        actions: set[str] = set()
        for arm in re.findall(r"^    ([^)\n]+)\)", case.group(1), re.M):
            actions |= {a.strip() for a in arm.split("|") if a.strip()}
        actions.discard("*")
        return actions

    def test_gui_only_calls_existing_helper_actions(self):
        valid = self._valid_actions()
        self.assertIn("restore-background", valid,
                      "helper lost its restore action entirely")
        called: set[str] = set()
        # e.g. subprocess.run(["sudo", HELPER, "restore-background"], ...)
        for call in re.findall(r"HELPER\s*,\s*[\"']([^\"']+)[\"']", self.gui_src):
            called.add(call)
        bad = sorted(called - valid)
        self.assertEqual(
            bad, [],
            f"the GUI calls helper actions that do not exist: {bad}. The helper "
            "exits 1 on an unknown action, so these calls silently do nothing "
            f"while the UI reports success. Valid actions: {sorted(valid)}",
        )

    def test_gui_does_not_report_unverified_success(self):
        """Any toast claiming a restore happened must come from a checked call.

        The old code toasted "all services resumed" unconditionally, before
        knowing whether the helper had run at all.
        """
        self.assertNotIn(
            "resume-background", self.gui_src,
            "GUI still calls the non-existent resume-background action",
        )
        resume_fn = re.search(
            r"def _run_restore_background\(self\):(.*?)(?=\n    def )",
            self.gui_src, re.S)
        self.assertIsNotNone(resume_fn, "_run_restore_background missing")
        body = resume_fn.group(1)
        self.assertIn("returncode", body,
                      "restore must check the helper's exit status")
        self.assertIn("_toast_error", body,
                      "a failed restore must be reported, not swallowed")


BOOT_MODE_PATH = "/usr/lib/raptor/cortex-apply-boot-mode"
BOOT_UNIT_PATH = "/usr/lib/systemd/user/raptor-cortex-mode.service"


class TestCortexBootMode(unittest.TestCase):
    """The persisted performance mode must actually be applied at boot.

    The GUI's "Apply selected mode on every boot" toggle only ever wrote
    ~/.config/raptor-cortex-mode. Nothing read that file at startup, so the
    mode was silently lost on every reboot and the CPU governor was set by
    gpu-detect.sh from the *GPU profile* instead. The UI described a feature
    that did not exist.
    """

    @classmethod
    def setUpClass(cls):
        payload = extract_file(SCRIPTS / "raptor-cortex.sh")
        cls.payload = payload
        assert BOOT_MODE_PATH in payload, f"{BOOT_MODE_PATH} not installed"
        assert BOOT_UNIT_PATH in payload, f"{BOOT_UNIT_PATH} not installed"
        script = Path(tempfile.mkdtemp(prefix="raptor-boot-")) / "boot-mode"
        script.write_text(payload[BOOT_MODE_PATH])
        script.chmod(0o755)
        cls.script = script

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="raptor-boot-home-"))
        (self.tmp / ".config").mkdir()
        (self.tmp / "bin").mkdir()
        self.calls = self.tmp / "calls.log"
        sudo = self.tmp / "bin" / "sudo"
        sudo.write_text(f'#!/bin/sh\nprintf "%s\\n" "$*" >> "{self.calls}"\n')
        sudo.chmod(0o755)
        helper = self.tmp / "helper"
        helper.write_text("#!/bin/sh\nexit 0\n")
        helper.chmod(0o755)
        self.helper = helper

    def _run(self, mode: str | None, settings: str | None = None) -> list[str]:
        if mode is not None:
            (self.tmp / ".config" / "raptor-cortex-mode").write_text(mode)
        if settings is not None:
            (self.tmp / ".config" / "raptor-cortex-settings.json").write_text(settings)
        self.calls.unlink(missing_ok=True)
        subprocess.run(
            [str(self.script)],
            env=dict(os.environ, HOME=str(self.tmp),
                     PATH=f"{self.tmp / 'bin'}:{os.environ['PATH']}",
                     RAPTOR_CORTEX_HELPER=str(self.helper)),
            capture_output=True, timeout=30,
        )
        if not self.calls.exists():
            return []
        return self.calls.read_text().split()

    def test_boot_script_is_valid_bash(self):
        proc = subprocess.run(["bash", "-n", str(self.script)],
                              capture_output=True, text=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)

    def test_each_persisted_mode_is_applied(self):
        for mode in ("performance", "balanced", "power_saving"):
            with self.subTest(mode=mode):
                self.assertEqual(
                    self._run(mode),
                    ["-n", str(self.helper), "set-mode", mode],
                    f"persisted mode {mode!r} was not applied at boot",
                )

    def test_trailing_whitespace_is_tolerated(self):
        """persist_mode() writes mode + "\n", so the file is never bare."""
        self.assertEqual(self._run("performance\n"),
                         ["-n", str(self.helper), "set-mode", "performance"])

    def test_junk_and_injection_are_rejected(self):
        """Only the three known modes may ever reach the helper.

        The mode file is user-writable, so it is untrusted input.
        """
        for junk in ("", "PERFORMANCE", "performance; reboot",
                     "'; rm -rf /", "$(reboot)", "balanced extra",
                     "../../etc/passwd"):
            with self.subTest(mode=junk):
                self.assertEqual(
                    self._run(junk), [],
                    f"untrusted mode value {junk!r} was passed to the helper",
                )

    def test_respects_the_apply_on_boot_preference(self):
        self.assertEqual(
            self._run("performance", '{"auto_apply_mode_on_boot": false}'), [],
            "the mode was applied even though the user opted out",
        )
        self.assertEqual(
            self._run("performance", '{"auto_apply_mode_on_boot": true}'),
            ["-n", str(self.helper), "set-mode", "performance"],
            "opting in did not apply the mode",
        )

    def test_no_mode_file_is_a_clean_no_op(self):
        self.assertEqual(self._run(None), [])

    def test_unit_runs_after_gpu_profile_so_cortex_governor_wins(self):
        """gpu-detect.sh also writes scaling_governor; Cortex's explicit
        choice must be applied after it, not before."""
        unit = self.payload[BOOT_UNIT_PATH]
        self.assertRegex(unit, r"After=.*raptor-gpu-profile\.service")
        self.assertIn("ExecStart=/usr/lib/raptor/cortex-apply-boot-mode", unit)
        # A failure here must never block the user's login.
        self.assertIn("SuccessExitStatus", unit)

    def test_installer_enables_the_boot_unit(self):
        installer = (SCRIPTS / "raptor-cortex.sh").read_text()
        self.assertRegex(
            installer,
            r"systemctl\s+--global\s+enable\s+raptor-cortex-mode\.service",
            "the boot-mode unit is installed but never enabled — the persisted "
            "mode would still be lost on reboot",
        )


class TestCortexFanSafety(unittest.TestCase):
    """Fan control writes to hardware, so every gate is tested.

    A wrong PWM value can leave a fan barely turning and cook the CPU, with
    nothing reporting it. The helper is driven against a fake sysfs tree so the
    refusal paths are exercised without a real fan controller.
    """

    @classmethod
    def setUpClass(cls):
        payload = extract_file(SCRIPTS / "raptor-cortex.sh")
        h = Path(tempfile.mkdtemp(prefix="raptor-fan-")) / "cortex-helper"
        h.write_text(payload[HELPER_PATH])
        h.chmod(0o755)
        cls.helper = h

    def _machine(self, chip="nct6798", rpm=2400, temp_c=55, pwm_enable=True,
                 fan_input=True) -> Path:
        root = Path(tempfile.mkdtemp(prefix="raptor-fan-sys-"))
        hw = root / "hw" / "hwmon0"
        hw.mkdir(parents=True)
        (hw / "name").write_text(chip)
        (hw / "pwm1").write_text("128")
        (hw / "pwm1_min").write_text("0")
        (hw / "pwm1_max").write_text("255")
        if pwm_enable:
            (hw / "pwm1_enable").write_text("0")
        if fan_input:
            (hw / "fan1_input").write_text(str(rpm))
        th = root / "th" / "thermal_zone0"
        th.mkdir(parents=True)
        (th / "type").write_text("x86_pkg_temp")
        (th / "temp").write_text(str(temp_c * 1000))
        return root

    def _run(self, root: Path, *args):
        return subprocess.run(
            [str(self.helper), *args], capture_output=True, text=True,
            env=dict(os.environ, RAPTOR_HWMON_ROOT=str(root / "hw"),
                     RAPTOR_THERMAL_ROOT=str(root / "th")),
            timeout=30,
        )

    def _pwm(self, root: Path) -> str:
        return (root / "hw" / "hwmon0" / "pwm1").read_text()

    def _enable(self, root: Path) -> str:
        return (root / "hw" / "hwmon0" / "pwm1_enable").read_text()

    def test_helper_never_depends_on_bc(self):
        """A missing `bc` used to yield an empty duty, which became 0 — the
        minimum fan speed — while reporting success."""
        src = self.helper.read_text()
        self.assertNotIn("bc |", src, "fan curve still shells out to bc")
        self.assertNotIn("| bc", src, "fan curve still shells out to bc")

    def test_curve_rises_monotonically_with_temperature(self):
        seen = []
        for temp_c in (35, 50, 60, 70, 78, 85):
            root = self._machine(temp_c=temp_c)
            self._run(root, "fan-profile", "turbo")
            seen.append(int(self._pwm(root)))
        self.assertEqual(seen, sorted(seen),
                         f"duty must never fall as temperature rises: {seen}")
        self.assertGreater(seen[-1], seen[0])

    def test_hot_cpu_interlocks_and_returns_control(self):
        root = self._machine(temp_c=95)
        out = self._run(root, "fan-profile", "turbo")
        self.assertIn("INTERLOCK", out.stderr)
        self.assertEqual(self._enable(root), "0",
                         "control must be handed back on a hot CPU")

    def test_stalled_fan_is_refused(self):
        root = self._machine(rpm=0)
        before = self._pwm(root)
        out = self._run(root, "fan-profile", "turbo")
        self.assertIn("REFUSED", out.stderr)
        self.assertEqual(self._pwm(root), before)

    def test_stalled_fan_override_is_explicit(self):
        root = self._machine(rpm=0)
        proc = subprocess.run(
            [str(self.helper), "fan-profile", "turbo"], capture_output=True,
            text=True,
            env=dict(os.environ, RAPTOR_HWMON_ROOT=str(root / "hw"),
                     RAPTOR_THERMAL_ROOT=str(root / "th"),
                     RAPTOR_FAN_IGNORE_STALLED="1"), timeout=30)
        self.assertNotIn("REFUSED", proc.stderr)

    def test_chip_outside_the_allowlist_is_never_written(self):
        for chip in ("asus", "ec", "acpitz", "amdgpu", "nouveau"):
            with self.subTest(chip=chip):
                root = self._machine(chip=chip)
                before = self._pwm(root)
                out = self._run(root, "fan-profile", "turbo")
                self.assertIn("REFUSED", out.stderr)
                self.assertEqual(self._pwm(root), before)
                self.assertEqual(self._enable(root), "0")

    def test_allowlisted_chip_without_rpm_readback_is_refused(self):
        root = self._machine(fan_input=False)
        before = self._pwm(root)
        out = self._run(root, "fan-profile", "turbo")
        self.assertIn("REFUSED", out.stderr)
        self.assertEqual(self._pwm(root), before,
                         "must not write PWM when RPM cannot confirm the fan spins")

    def test_allowlisted_chip_without_pwm_enable_is_refused(self):
        root = self._machine(pwm_enable=False)
        before = self._pwm(root)
        self._run(root, "fan-profile", "turbo")
        self.assertEqual(self._pwm(root), before)

    def test_turbo_never_reaches_full_duty(self):
        """100% is excluded on purpose: a stuck maximum is not the failure
        mode we are willing to risk."""
        root = self._machine(temp_c=95)
        # 95C interlocks, so check the curve at its hottest applying point.
        root = self._machine(temp_c=88)
        self._run(root, "fan-profile", "turbo")
        self.assertLess(int(self._pwm(root)), 255,
                        "turbo wrote full duty; the hard cap is not working")

    def test_silent_profile_never_writes_a_stopped_fan(self):
        root = self._machine(temp_c=35)
        self._run(root, "fan-profile", "silent")
        self.assertGreater(int(self._pwm(root)), 0)

    def test_fan_auto_restores_driver_control(self):
        root = self._machine()
        (root / "hw" / "hwmon0" / "pwm1_enable").write_text("1")
        out = self._run(root, "fan-auto")
        self.assertEqual(out.returncode, 0)
        self.assertEqual(self._enable(root), "0")

    def test_fan_info_is_read_only_and_works_without_control(self):
        root = self._machine(chip="acpitz")
        before_pwm, before_enable = self._pwm(root), self._enable(root)
        out = self._run(root, "fan-info")
        self.assertEqual(out.returncode, 0)
        self.assertIn("read-only", out.stdout)
        self.assertEqual(self._pwm(root), before_pwm)
        self.assertEqual(self._enable(root), before_enable)

    def test_unknown_profile_is_rejected(self):
        root = self._machine()
        for bad in ("nuke", "", "TURBO", "balanced; reboot"):
            with self.subTest(profile=bad):
                out = self._run(root, "fan-profile", bad)
                self.assertEqual(out.returncode, 1)
                self.assertIn("Usage", out.stderr)


class TestCortexSudoers(unittest.TestCase):

    def test_sudoers_grants_the_helper_without_password(self):
        payload = extract_file(SCRIPTS / "raptor-cortex.sh")
        rule = payload["/etc/sudoers.d/raptor-cortex"]
        self.assertIn("NOPASSWD", rule)
        self.assertIn(HELPER_PATH, rule)


class TestSudoersAlwaysValidated(unittest.TestCase):
    """Every sudoers drop-in must be validated, and validation must be fatal.

    sudo silently ignores an entire malformed file in /etc/sudoers.d. So an
    unvalidated drop-in that goes bad ships green in CI and then breaks every
    privileged call in the app for every user, with nothing in the logs.
    """

    def _sudoers_paths(self, installer: Path) -> list[str]:
        return [p for p in extract_file(installer) if "/sudoers.d/" in p]

    def test_every_sudoers_dropin_is_visudo_validated(self):
        found_any = False
        for installer in sorted(SCRIPTS.glob("*.sh")):
            for path in self._sudoers_paths(installer):
                found_any = True
                with self.subTest(installer=installer.name, dropin=path):
                    text = installer.read_text()
                    self.assertIn(
                        "visudo", text,
                        f"{installer.name} writes {path} but never validates it — "
                        "sudo ignores a malformed drop-in entirely, so a bad "
                        "file silently breaks the app for everyone",
                    )
                    self.assertNotIn(
                        f"visudo -cf {path} || true", text,
                        f"{installer.name}: sudoers validation of {path} is "
                        "discarded, so a broken file ships silently",
                    )
                    self.assertNotIn(
                        f"visudo -c -f {path} >/dev/null &&", text,
                        f"{installer.name}: sudoers validation of {path} is "
                        "chained with && so a failure cannot stop the build",
                    )
        self.assertTrue(found_any, "no sudoers drop-ins found — tests are vacuous")


if __name__ == "__main__":
    unittest.main(verbosity=2)
