#!/usr/bin/env python3
"""Regression tests for the Raptor OS Update Manager.

These run the *exact* payload the installer ships (extracted from the heredocs
in raptor-update.sh) with stubbed `rpm-ostree` / `sudo` / `curl` / `skopeo`, so
the update manager's decision logic is verified in CI instead of being guessed
at and re-fixed on a user's machine.

Run:  python3 files/scripts/tests/test_update_manager.py
"""
from __future__ import annotations

import os
import shutil
import stat
import subprocess
import sys
import tempfile
import time
import textwrap
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent
sys.path.insert(0, str(HERE))

from extract import extract_file  # noqa: E402

INSTALLER = SCRIPTS / "raptor-update.sh"
PAYLOAD = extract_file(INSTALLER)


def _materialise(root: Path, install_path: str) -> Path:
    """Write a generated payload to `root/<install_path without leading />`."""
    dest = root / install_path.lstrip("/")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(PAYLOAD[install_path])
    dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return dest


def _stub(bin_dir: Path, name: str, body: str) -> None:
    p = bin_dir / name
    p.write_text("#!/bin/bash\n" + textwrap.dedent(body).lstrip())
    p.chmod(0o755)


class _Sandbox:
    """Temp dir with a stub-first PATH."""

    def __init__(self) -> None:
        self.root = Path(tempfile.mkdtemp(prefix="raptor-ut-"))
        self.bin = self.root / "bin"
        self.bin.mkdir()
        self._saved_path = os.environ["PATH"]

    def __enter__(self) -> "_Sandbox":
        os.environ["PATH"] = f"{self.bin}{os.pathsep}{self._saved_path}"
        return self

    def __exit__(self, *exc) -> None:
        os.environ["PATH"] = self._saved_path
        shutil.rmtree(self.root, ignore_errors=True)

    def stub(self, name: str, body: str) -> None:
        _stub(self.bin, name, body)

    def run(self, script: Path, *args: str, env: dict | None = None,
            timeout: int = 60) -> subprocess.CompletedProcess:
        e = dict(os.environ)
        e.update(env or {})
        return subprocess.run(
            ["bash", str(script), *args],
            capture_output=True, text=True, timeout=timeout, env=e,
        )


# ── generated payload must exist at all ───────────────────────────────────────
class TestPayloadShape(unittest.TestCase):
    def test_all_expected_files_are_generated(self):
        for p in (
            "/usr/lib/raptor/update-helper",
            "/usr/lib/raptor/check-helper",
            "/usr/lib/raptor/flatpak-update-helper",
            "/usr/lib/raptor/reboot-helper",
            "/usr/bin/raptor-update",
            "/usr/bin/raptor-update-launcher",
            "/usr/share/applications/raptor-update.desktop",
            "/etc/sudoers.d/raptor-update",
        ):
            self.assertIn(p, PAYLOAD, f"installer no longer generates {p}")

    def test_desktop_entry_points_at_a_file_the_installer_creates(self):
        """The .desktop Exec= target must exist in the generated payload.

        A mismatch here means the app menu silently does nothing: the entry
        resolves, GNOME hides it, and the update manager looks 'missing' with
        no error anywhere.
        """
        desktop = PAYLOAD["/usr/share/applications/raptor-update.desktop"]
        exec_line = next(
            ln for ln in desktop.splitlines() if ln.startswith("Exec=")
        )
        target = exec_line.split("=", 1)[1].strip()
        self.assertIn(
            target, PAYLOAD,
            f"desktop Exec={target} is never generated by the installer",
        )

    def test_sudoers_grants_nopasswd_for_every_helper(self):
        sudoers = PAYLOAD["/etc/sudoers.d/raptor-update"]
        for helper in (
            "/usr/lib/raptor/update-helper",
            "/usr/lib/raptor/check-helper",
            "/usr/lib/raptor/flatpak-update-helper",
            "/usr/lib/raptor/reboot-helper",
        ):
            self.assertIn(f"NOPASSWD: {helper}", sudoers)

    def test_invalid_sudoers_fails_the_build(self):
        """A malformed sudoers drop-in must not be installed silently.

        sudo ignores an entire unparseable file in /etc/sudoers.d, so `sudo -n`
        starts refusing and the update manager is dead on a freshly booted
        image with nothing shown to the user.
        """
        installer = INSTALLER.read_text()
        self.assertNotIn(
            "visudo -cf /etc/sudoers.d/raptor-update || true",
            installer,
            "sudoers validation failure is still being ignored",
        )
        self.assertIn("FATAL: /etc/sudoers.d/raptor-update is invalid", installer)

    def test_helper_budgets_have_sane_defaults(self):
        """Overrides are for tests only — the shipped values must be unchanged."""
        check = PAYLOAD["/usr/lib/raptor/check-helper"]
        self.assertIn('RAPTOR_CHECK_MAX_ATTEMPTS:-3', check)
        self.assertIn('RAPTOR_CHECK_ATTEMPT_TIMEOUT:-150', check)
        update = PAYLOAD["/usr/lib/raptor/update-helper"]
        self.assertIn('RAPTOR_UPDATE_MAX_ATTEMPTS:-3', update)
        self.assertIn('RAPTOR_UPDATE_LAYER_TIMEOUT:-900', update)


# ── check-helper verdict logic ────────────────────────────────────────────────
class TestCheckHelper(unittest.TestCase):
    def _run_check(self, sb, upgrade_body, *, curl_ok=True, skopeo=True,
                   jq=True, local_digest=None, remote_digest=None):
        sb.stub("curl", f"exit {0 if curl_ok else 1}")
        sb.stub("rpm-ostree", upgrade_body)
        if not skopeo:
            # "not installed" == the command is absent from PATH
            pass
        else:
            sb.stub("skopeo", textwrap.dedent(f"""
                if [ "${{1:-}}" = "inspect" ] && [ "${{2:-}}" = "--raw" ]; then
                  printf '%s' "${{STUB_MANIFEST:-{{}}}}"
                  exit 0
                fi
                echo "${{STUB_REMOTE_DIGEST:-}}"
            """))
        if jq:
            sb.stub("jq", textwrap.dedent("""
                if [ "$1" = "-e" ]; then
                  grep -q manifests && exit 0 || exit 1
                fi
                case "$*" in
                  *".deployments[0].origin"*) echo "${STUB_ORIGIN:-}" ;;
                  *container-image-reference-digest*) echo "${STUB_LOCAL_DIGEST:-}" ;;
                  *ostree.manifest-digest*) echo "" ;;
                  *".manifests[]"*) echo "${STUB_MANIFEST_DIGEST:-}" ;;
                  *) cat ;;
                esac
            """))
        else:
            sb.stub("jq", "echo ''")
        env = {
            "STUB_ORIGIN": "ostree-image-signed:docker://ghcr.io/x/y:stable",
            "STUB_LOCAL_DIGEST": local_digest or "",
            "STUB_REMOTE_DIGEST": remote_digest or "",
            "STUB_MANIFEST_DIGEST": remote_digest or "",
        }
        return sb.run(_materialise(sb.root, "/usr/lib/raptor/check-helper"), env=env)

    def test_explicit_available_update_exits_zero(self):
        with _Sandbox() as sb:
            r = self._run_check(sb, """
                echo "AvailableUpdate: ghcr.io/x/y:stable"
                exit 0
            """)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertIn("AvailableUpdate", r.stdout)

    def test_clean_check_is_not_mistaken_for_failure(self):
        """Exit 0 + 'No updates available.' must NOT be reported as an error."""
        with _Sandbox() as sb:
            r = self._run_check(sb, """
                echo "No updates available."
                exit 0
            """)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertNotIn("Could not refresh", r.stdout)

    def test_clean_check_exit_77_is_success(self):
        with _Sandbox() as sb:
            r = self._run_check(sb, """
                echo "No updates available."
                exit 77
            """)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)

    def test_registry_digest_mismatch_announces_update(self):
        """The container-native trap: rpm-ostree says 'no updates' but the
        registry tag moved. The cross-check must still announce it."""
        with _Sandbox() as sb:
            r = self._run_check(
                sb,
                """
                echo "No updates available."
                exit 0
                """,
                local_digest="sha256:aaaa",
                remote_digest="sha256:bbbb",
            )
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertIn("AvailableUpdate", r.stdout)
        self.assertIn("sha256:bbbb", r.stdout)

    def test_registry_digest_match_announces_nothing(self):
        with _Sandbox() as sb:
            r = self._run_check(
                sb,
                """
                echo "No updates available."
                exit 0
                """,
                local_digest="sha256:aaaa",
                remote_digest="sha256:aaaa",
            )
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertNotIn("AvailableUpdate", r.stdout)

    def test_hard_failure_is_reported_as_failure(self):
        with _Sandbox() as sb:
            r = self._run_check(sb, """
                echo "error: could not reach registry" >&2
                exit 1
            """, skopeo=False)
        self.assertNotEqual(r.returncode, 0)
        self.assertIn("Could not refresh", r.stdout)

    def test_never_hangs_past_its_attempt_budget(self):
        """A stalled rpm-ostree must be bounded, not hang the GUI forever.

        Real budgets are 3 × 150 s; the helper reads them from the
        RAPTOR_CHECK_* env vars (defaults unchanged) so this runs in seconds.
        """
        with _Sandbox() as sb:
            sb.stub("curl", "exit 0")
            sb.stub("timeout", """
                # Emulate `coreutils timeout <secs> <cmd>`: run the child in
                # its own session so we can kill the whole group, otherwise
                # the orphaned child keeps the captured stdout pipe open and
                # the test harness blocks long after the helper gave up.
                secs="${1:-0}"; shift
                setsid "$@" & pid=$!
                ( sleep "$secs"; kill -9 -- -"$pid" 2>/dev/null ) & watcher=$!
                wait "$pid" 2>/dev/null; rc=$?
                kill -9 -- -"$pid" 2>/dev/null
                kill -9 "$watcher" 2>/dev/null
                exit $rc
            """)
            sb.stub("rpm-ostree", "sleep 3600")
            started = time.monotonic()
            r = sb.run(
                _materialise(sb.root, "/usr/lib/raptor/check-helper"),
                env={
                    "RAPTOR_CHECK_MAX_ATTEMPTS": "2",
                    "RAPTOR_CHECK_ATTEMPT_TIMEOUT": "1",
                    "RAPTOR_CHECK_RETRY_SLEEP": "0",
                },
                timeout=60,
            )
            elapsed = time.monotonic() - started
        self.assertIn(r.returncode, (0, 1))
        self.assertIn("Could not refresh", r.stdout)
        self.assertLess(elapsed, 30, "check-helper exceeded its attempt budget")


# ── update-helper retry logic ─────────────────────────────────────────────────
class TestUpdateHelper(unittest.TestCase):
    FAST = {
        "RAPTOR_UPDATE_MAX_ATTEMPTS": "3",
        "RAPTOR_UPDATE_LAYER_TIMEOUT": "5",
        "RAPTOR_UPDATE_BACKOFF": "0",
        "RAPTOR_UPDATE_NET_WAIT": "0",
    }

    def test_succeeds_after_transient_failure(self):
        with _Sandbox() as sb:
            sb.stub("curl", "exit 0")
            sb.stub("sleep", "exit 0")
            sb.stub("timeout", 'shift; exec "$@"')
            sb.stub("rpm-ostree", """
                n=$(cat "${STATE}" 2>/dev/null || echo 0)
                n=$((n + 1)); echo "$n" > "${STATE}"
                if [ "$n" -lt 3 ]; then
                    echo "Processing tar: unexpected end of file" >&2
                    exit 1
                fi
                echo "Update applied."
                exit 0
            """)
            sb.stub("rm", """
                # let the real rm work, but track the calls that matter
                if [ "$1" = "-rf" ] && [ "$2" = "/var/cache/rpm-ostree-layers" ]; then
                    echo purged >> "${STATE}.purges"
                fi
                exec /bin/rm "$@"
            """)
            r = sb.run(
                _materialise(sb.root, "/usr/lib/raptor/update-helper"),
                env={"STATE": str(sb.root / "state"), **self.FAST},
            )
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertIn("Attempt 3/3", r.stdout)
        self.assertIn("Update applied", r.stdout)

    def test_gives_up_after_max_attempts(self):
        with _Sandbox() as sb:
            sb.stub("curl", "exit 0")
            sb.stub("sleep", "exit 0")
            sb.stub("timeout", 'shift; exec "$@"')
            sb.stub("rpm-ostree", "echo boom >&2; exit 1")
            sb.stub("rm", 'exec /bin/rm "$@"')
            r = sb.run(
                _materialise(sb.root, "/usr/lib/raptor/update-helper"),
                env={"STATE": str(sb.root / "state"), **self.FAST},
            )
        self.assertNotEqual(r.returncode, 0)
        self.assertIn("Update failed", r.stdout)


# ── GUI: privilege escalation + verdict matrix ────────────────────────────────
def _load_gui_module():
    import gi_stub

    gi_stub.install()
    src = PAYLOAD["/usr/bin/raptor-update"]
    mod = type(sys)("raptor_update_gui")
    mod.__file__ = "/usr/bin/raptor-update"
    exec(compile(src, "/usr/bin/raptor-update", "exec"), mod.__dict__)
    return mod


def _set_sudoers(gui, sb, granted: bool, *, commented_out: bool = False) -> None:
    """Materialise a sudoers drop-in the way the installer would.

    run_privileged() picks its launcher from what the drop-in grants, so the
    on-disk state is what drives the decision under test.
    """
    if granted:
        body = "\n".join(
            f"{'# ' if commented_out else ''}ALL ALL=(root) NOPASSWD: {h}"
            for h in (
                "/usr/lib/raptor/update-helper",
                "/usr/lib/raptor/check-helper",
                "/usr/lib/raptor/flatpak-update-helper",
                "/usr/lib/raptor/reboot-helper",
            )
        )
    else:
        body = ""
    target = sb.root / "sudoers.d" / "raptor-update"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body + "\n")
    gui.SUDOERS_FILE = str(target)


def _sudo_stub(sb, *, granted: bool, body: str = 'exec "$@"', gui=None) -> None:
    """A sudo stub plus the sudoers grant that decides which launcher wins."""
    if gui is not None:
        _set_sudoers(gui, sb, granted)
    sb.stub("sudo", body)


class TestRunPrivileged(unittest.TestCase):
    """`sudo -n` failing must still fall through to pkexec.

    subprocess.Popen only raises FileNotFoundError when the *binary* is
    missing. When sudo exists but refuses (missing/stale NOPASSWD rule,
    password required), Popen succeeds and the caller is handed a process
    that is already dead — so a naive launcher never reaches the fallback.
    """

    def setUp(self):
        self.gui = _load_gui_module()

    def _set_sudoers(self, sb, granted, *, commented_out=False):
        _set_sudoers(self.gui, sb, granted, commented_out=commented_out)

    def _sudo_stub(self, sb, *, allowed, body='exec "$@"'):
        _sudo_stub(sb, granted=allowed, body=body, gui=self.gui)

    def test_missing_sudo_binary_falls_back_to_pkexec(self):
        with _Sandbox() as sb:
            self._set_sudoers(sb, granted=True)
            sb.stub("pkexec", "exit 0")
            proc = self.gui.run_privileged("/usr/lib/raptor/check-helper")
            self.assertEqual(proc.args[0], "pkexec")
            proc.wait()

    def test_sudo_without_a_grant_falls_back_to_pkexec(self):
        """The broken-install case: sudo exists, NOPASSWD rule does not.

        This is what used to leave the user staring at
        "Could not refresh update state (sudo: a password is required)".
        """
        with _Sandbox() as sb:
            self._set_sudoers(sb, granted=False)
            sb.stub("sudo", 'echo "sudo: a password is required" >&2; exit 1')
            sb.stub("pkexec", "exit 0")
            proc = self.gui.run_privileged("/usr/lib/raptor/check-helper")
            self.assertEqual(
                proc.args[0], "pkexec",
                "pkexec fallback was never reached after sudo refused",
            )
            proc.wait()

    def test_missing_sudoers_file_falls_back_to_pkexec(self):
        with _Sandbox() as sb:
            self.gui.SUDOERS_FILE = str(sb.root / "does-not-exist")
            sb.stub("sudo", 'echo "sudo: a password is required" >&2; exit 1')
            sb.stub("pkexec", "exit 0")
            proc = self.gui.run_privileged("/usr/lib/raptor/check-helper")
            self.assertEqual(proc.args[0], "pkexec")
            proc.wait()

    def test_commented_out_rule_is_not_treated_as_a_grant(self):
        with _Sandbox() as sb:
            self._set_sudoers(sb, granted=True, commented_out=True)
            sb.stub("sudo", 'echo "sudo: a password is required" >&2; exit 1')
            sb.stub("pkexec", "exit 0")
            proc = self.gui.run_privileged("/usr/lib/raptor/check-helper")
            self.assertEqual(proc.args[0], "pkexec")
            proc.wait()

    def test_healthy_grant_uses_sudo_without_prompting(self):
        """A working install must keep using the silent sudo path.

        Regression guard: an over-eager probe (e.g. `sudo -n -l`, which can
        require auth on a stock wheel+NOPASSWD setup) would push every user
        onto a polkit password prompt.
        """
        with _Sandbox() as sb:
            self._set_sudoers(sb, granted=True)
            sb.stub("sudo", 'exec "$@"')
            sb.stub("pkexec", 'echo "pkexec must not run" >&2; exit 9')
            proc = self.gui.run_privileged("/usr/lib/raptor/check-helper")
            self.assertEqual(proc.args[0], "sudo")
            proc.wait()

    def test_still_tries_sudo_when_sudoers_cannot_be_read(self):
        """Never lock the user out on a false negative."""
        with _Sandbox() as sb:
            self.gui.SUDOERS_FILE = str(sb.root / "unreadable")
            sb.stub("sudo", 'exec "$@"')
            proc = self.gui.run_privileged("/usr/lib/raptor/check-helper")
            self.assertEqual(proc.args[0], "sudo")
            proc.wait()

    def test_no_launcher_available_raises_actionable_error(self):
        with _Sandbox() as sb:
            self._set_sudoers(sb, granted=True)
            # Neither binary on PATH: shutil.which finds nothing.
            saved = os.environ["PATH"]
            os.environ["PATH"] = str(sb.bin)
            try:
                with self.assertRaises(RuntimeError) as ctx:
                    self.gui.run_privileged("/usr/lib/raptor/check-helper")
            finally:
                os.environ["PATH"] = saved
        self.assertIn("raptor-update", str(ctx.exception))


class TestCheckForUpdates(unittest.TestCase):
    def setUp(self):
        self.gui = _load_gui_module()

    def _decide(self, sb, *, check_out="", check_rc=0, status_json=None,
                status_rc=0):
        _set_sudoers(self.gui, sb, granted=True)
        sb.stub("sudo", f'''
            cat <<'EOT'
{check_out}
EOT
            exit {check_rc}
        ''')
        sb.stub("rpm-ostree", """
            if [ "$1" = "status" ]; then
                cat <<'EOT'
        %s
        EOT
                exit %d
            fi
            exit 1
        """ % (status_json or "{}", status_rc))
        return self.gui.check_for_updates()

    def test_explicit_available_update(self):
        with _Sandbox() as sb:
            has, msg = self._decide(sb, check_out="AvailableUpdate: new")
        self.assertTrue(has, msg)

    def test_clean_reports_up_to_date(self):
        with _Sandbox() as sb:
            has, msg = self._decide(
                sb,
                check_out="No updates available.",
                status_json='{"deployments":[{"booted":true}]}',
            )
        self.assertFalse(has, msg)
        self.assertIn("up to date", msg.lower())

    def test_cached_update_field_is_honoured(self):
        with _Sandbox() as sb:
            has, msg = self._decide(
                sb,
                check_out="No updates available.",
                status_json='{"deployments":[{"booted":true,'
                            '"cached-update":"ostree:ghcr.io/x/y"}]}',
            )
        self.assertTrue(has, msg)

    def test_staged_unbooted_deployment_is_honoured(self):
        with _Sandbox() as sb:
            has, msg = self._decide(
                sb,
                check_out="No updates available.",
                status_json='{"deployments":[{"booted":false}]}',
            )
        self.assertTrue(has, msg)

    def test_refresh_failure_is_surfaced_not_silently_ok(self):
        with _Sandbox() as sb:
            has, msg = self._decide(
                sb,
                check_out="error: DNS failure",
                check_rc=1,
                status_json='{"deployments":[{"booted":true}]}',
            )
        self.assertFalse(has)
        self.assertNotIn("up to date", msg.lower())

    def test_refresh_failure_does_not_hide_a_locally_staged_update(self):
        with _Sandbox() as sb:
            has, msg = self._decide(
                sb,
                check_out="error: DNS failure",
                check_rc=1,
                status_json='{"deployments":[{"booted":false}]}',
            )
        self.assertTrue(has, "a locally staged update must still be reported")


if __name__ == "__main__":
    unittest.main(verbosity=2)
